name: CustomAuth
version: 1.0.1
main: Codeh\CustomAuth\leMain
api: [3.5.0, 4.0.0]
description: A custom auth
author: ItzCodeeeh

commands:
  login:
    description: "testing"
  logout:
    description: "testing"
  register:
    description: "testing"
