name: CustomAuth
version: 1.0.1
main: Codeh\CustomAuth\leMain
api: [3.5.0, 4.0.0]
description: A custom auth
author: ItzCodeeeh

commands:
  login:
    description: " Let's you input your password."
  logout:
    description: " Logs you out (which is nonsense btw)."
  register:
    description: " Let's you get rid of your nasty Xbox Gamertag."
